#!/bin/sh /etc/rc.common

START=50

USE_PROCD=1

UHTTPD_BIN="/usr/sbin/uhttpd"

start_service() {
	# -wusel, 20220503: Allow access from RFC1918, TEST-NET-?, Link-Local & ULA 
	/usr/sbin/iptables -I INPUT -s 10.0.0.0/8 -p tcp --dport 80 -j ACCEPT ||:
	/usr/sbin/iptables -I INPUT -s 172.16.0.0/12 -p tcp --dport 80 -j ACCEPT ||:
	/usr/sbin/iptables -I INPUT -s 192.168.0.0/16 -p tcp --dport 80 -j ACCEPT ||:
	/usr/sbin/iptables -I INPUT -s 203.0.113.0/24 -p tcp --dport 80 -j ACCEPT ||:
	/usr/sbin/iptables -I INPUT -s 10.0.0.0/8 -p tcp --dport 22 -j ACCEPT ||:
	/usr/sbin/iptables -I INPUT -s 172.16.0.0/12 -p tcp --dport 22 -j ACCEPT ||:
	/usr/sbin/iptables -I INPUT -s 192.168.0.0/16 -p tcp --dport 22 -j ACCEPT ||:
	/usr/sbin/iptables -I INPUT -s 203.0.113.0/24 -p tcp --dport 22 -j ACCEPT ||:
	/usr/sbin/ip6tables -I INPUT -s fe80::/10 -p tcp --dport 80 -j ACCEPT ||:
	/usr/sbin/ip6tables -I INPUT -s fc00::/7 -p tcp --dport 80 -j ACCEPT ||:
	/usr/sbin/ip6tables -I INPUT -s fe80::/10 -p tcp --dport 22 -j ACCEPT ||:
	/usr/sbin/ip6tables -I INPUT -s fc00::/7 -p tcp --dport 22 -j ACCEPT ||:
	procd_open_instance
	procd_set_param respawn
	procd_set_param command "$UHTTPD_BIN" -f -h /lib/gluon/config-mode/www -x /cgi-bin -A 1 -R -p 0.0.0.0:80
	procd_close_instance
}
